### PR TITLE
Vagrant

### PR DESCRIPTION
**Pull request by pietromenna**
I added Vagrant support. 

My idea is to allow future recursers who would like to contribute to have an easy way to setup the development environment.

Let me know if I need to change anything!

### CODE REVIEW

**Comment by zachallaun** [comment]
Wow, this is an awesome contribution! Thanks so much. I'll go through this soon.

**Comment by pietromenna** [comment]
Thanks! Please, let me know if I need to change anything in the commits.

**Comment by davidbalbert** [comment]
This is awesome!

Something I would like to be able to do is easily update versions of software that we use (Ruby, Postgres, Elasticsearch, Redis, etc.). Ideally, I'd like to be able to change a package version in a config file and have the new version installed the next time someone ran `vagrant up`. I think this might be possible with something like Ansible, Chef, or Salt, all of which Vagrant supports as provisioners, but I don't think how hard this would be.

@pietromenna is this doable?

**Comment by pietromenna** [comment]
Hi @davidbalbert ,

I am working on the Ansible version. I will think I might be able to have a working version by tomorrow, but It will be on a different branch of my fork. I will have to learn how to send this "new" branch to this PR.

**Comment by pietromenna** [comment]
I am not sure if this pull request is still required since the VM image has been created.

**Pull request closed without merging**
